import { fetchJson, bindPasswordToggle } from './admin-client.js';
const errorMessage = e => e instanceof TypeError ? '서버에 연결하지 못했습니다. 네트워크를 확인해 주세요.' : e.message;
const $ = selector => document.querySelector(selector);
const initial=$('[data-initial-view]'),login=$('[data-login-view]'),board=$('[data-board-view]'),form=$('[data-login-form]'),status=$('[data-status]'),output=$('[data-summary]');
bindPasswordToggle(form.elements.password,$('[data-password-toggle]'));
const names={payment_pending:'결제 대기',confirmed:'주문 확인',preparing:'배송 준비',shipped:'배송 중',delivered:'배송 완료',cancel_requested:'취소 요청',cancelled:'취소 완료',refund_requested:'반품·환불 요청',refunded:'환불 완료'};
function element(tag,text,className=''){const el=document.createElement(tag);el.textContent=text;if(className)el.className=className;return el;}
function section(title){const el=element('section','','ops-section');el.append(element('h2',title));output.append(el);return el;}
function render(data){
 output.replaceChildren();const grid=element('div','','ops-grid');for(const [key,label] of Object.entries(names)){const card=element('div','','ops-card');card.append(element('span',label),element('strong',`${data.counts[key]||0}건`));grid.append(card);}output.append(grid);
 const ready=section('판매·연동 상태');for(const text of [data.readiness.payment,data.readiness.canonical,data.readiness.inventory,data.readiness.mail?'주문 메일 발송 설정 있음 — 실제 발송 결과는 아래에서 확인하세요.':'주문 메일 발송 설정 필요',`실측·무게·소재 정보 미완성 ${data.inventory.incompleteSpecs}개 · 재고 미등록 ${data.inventory.unknown}개`])ready.append(element('p',text));
 const pending=section('오래된 결제 대기 주문 · 최대 20건');pending.append(element('p','결제 대기 단계에서는 재고를 예약하지 않습니다. 결제사 미연결 상태이므로 자동으로 취소하지 않습니다. 주문 관리에서 접수 내용을 확인하세요.'));
 for(const order of data.pending){const a=element('a',`${order.order_number} · ${new Date(order.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})} · ${Number(order.total).toLocaleString('ko-KR')}원`);a.href='orders.html';const line=element('p','');line.append(a);pending.append(line);}if(!data.pending.length)pending.append(element('p','결제 대기 주문이 없습니다.'));
 const stock=section('자사몰 할당 재고 5개 이하 · 최대 30개');for(const p of data.inventory.low){const a=element('a',`${p.name} · ${p.stock}개`);a.href='products.html';const line=element('p','');line.append(a);stock.append(line);}if(!data.inventory.low.length)stock.append(element('p','재고가 등록된 제품 중 5개 이하인 제품이 없습니다.'));
 const mail=section('주문 알림');const retry=element('button','실패 알림 최대 3건 재시도','button button--quiet');retry.type='button';retry.addEventListener('click',async()=>{retry.disabled=true;try{const result=await fetchJson('/api/admin/orders?route=ops-retry-notifications',{method:'POST',body:'{}'});await load();status.textContent=`알림 ${result.processed}건 처리 · ${result.sent}건 발송 완료`;}catch(e){status.textContent=errorMessage(e);}finally{retry.disabled=false;}});if(data.canRetry)mail.append(retry);mail.append(element('p',`발송 완료 ${data.notifications.sent||0}건 · 실패 ${data.notifications.failed||0}건 · 처리 중 ${data.notifications.pending||0}건 · 수동 확인 ${data.notifications.manual_review||0}건`));mail.append(element('p','최근 23시간 이내·현재 주문 상태와 같은 알림만 최대 5회 재시도합니다. 이전 알림과 오래된 실패는 수동 확인이 필요합니다. 메일 발송 실패가 주문 상태를 되돌리지는 않습니다.'));
 if(data.audit.length){const audit=section('최근 관리자 변경 기록 · 30건');const list=element('ol','');for(const row of data.audit)list.append(element('li',`${new Date(row.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} · ${row.actor} · ${row.action} · ${{success:'완료',failed:'실패',pending:'처리 결과 확인 필요'}[row.status]||row.status}`));audit.append(list);}
 status.textContent=`${new Date(data.checkedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} 기준`;
}
async function load(){const refresh=$('[data-refresh]');refresh.disabled=true;status.textContent='운영 현황을 확인하고 있습니다.';try{const data=await fetchJson('/api/admin/orders?route=ops-summary');login.hidden=true;board.hidden=false;render(data);}catch(e){if(e.status===401){login.hidden=false;board.hidden=true;}else{board.hidden=false;output.replaceChildren();status.textContent=errorMessage(e)+' 새로고침으로 다시 시도해 주세요.';}}finally{initial.hidden=true;refresh.disabled=false;}}
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('[type="submit"]');button.disabled=true;try{await fetchJson('/api/admin/session',{method:'POST',body:JSON.stringify({password:form.elements.password.value})});form.reset();await load();$('[data-title]').focus();}catch(e){$('[data-login-status]').textContent=errorMessage(e);}finally{button.disabled=false;}});
$('[data-refresh]').addEventListener('click',load);
$('[data-logout]').addEventListener('click',async()=>{try{await fetchJson('/api/admin/session',{method:'DELETE'});output.replaceChildren();board.hidden=true;login.hidden=false;form.elements.password.focus();}catch(e){status.textContent=errorMessage(e);}});
load();
